import { apiDelete, apiGet, apiPost, apiPut } from '../client'

const MOCK_AUTH = process.env.NEXT_PUBLIC_AUTH_MOCK === 'true'

// Confirmed via a real GET /api/v1/academic/batches response and
// Scheduling/Batches/*.bru. A batch is students enrolled in a specific
// program-semester combination for a given intake. intProgram/intSem/
// intStream/batchTime are all legacy int FKs with NO confirmed guid-based
// counterpart anywhere reachable from the frontend — ProgramMaster, Stream,
// BatchTime, and Semester (DropdownForProgram) all only expose guids, even
// in their dedicated dropdown endpoints. Don't guess label mappings for
// display — show the raw numbers, same convention as Enquiry's
// enquirySource/enquiryStatus.
export interface Batch {
  batchGuid: string
  batchCode: string
  intProgram: number
  intSem: number
  intStream: number
  batchTime: number
  bStartDate: string | null
  bEndDate: string | null
  // 0/1 flag, not a multi-value enum — same convention as country.ts's
  // defaultCountry.
  active: number
}

interface BatchListResult {
  items: Batch[]
  totalCount: number
  pageNumber: number
  pageSize: number
}

// Confirmed via Create.bru. intProgram/intSem/intStream/batchTime/
// bInCharge/intakeCode: required, > 0. bStartDate/bEndDate: optional.
// intakeCode is the one field here with a real confirmed source
// (Intake.intakeCode) — the rest have no guid-based master exposing a
// matching int, see the note on Batch above.
export interface BatchCreateInput {
  intProgram: number
  intSem: number
  intStream: number
  batchTime: number
  bStartDate: string | null
  bEndDate: string | null
  bInCharge: number
  intakeCode: number
}

// Confirmed via Update.bru: only intStream/bStartDate/bEndDate/bInCharge
// are actually applied by the backend. batchCode and batchTime are accepted
// in the body (both required as non-empty/>0 by validation) but are NOT
// applied — batchCode is immutable after creation, batchTime is currently
// ignored server-side. Callers should just echo back the existing record's
// batchCode/batchTime rather than offering a picker for either.
export interface BatchUpdateInput {
  batchCode: string
  batchTime: number
  intStream: number
  bStartDate: string | null
  bEndDate: string | null
  bInCharge: number
}

let mockBatchSeq = 1

const mockBatches: Batch[] = [
  { batchGuid: 'd7b04278-21ef-4cfa-8bee-ff336f08e344', batchCode: 'CSF26MRNA', intProgram: 1, intSem: 1, intStream: 1, batchTime: 1, bStartDate: '2024-02-12T00:00:00', bEndDate: '2024-06-07T00:00:00', active: 1 },
]

// Lists batches (paginated).
export function getBatches(pageNumber = 1, pageSize = 20): Promise<BatchListResult> {
  if (MOCK_AUTH) {
    return Promise.resolve({ items: mockBatches, totalCount: mockBatches.length, pageNumber, pageSize })
  }
  return apiGet<BatchListResult | null>(`/api/v1/academic/batches?pageNumber=${pageNumber}&pageSize=${pageSize}`)
    .then(data => data ?? { items: [], totalCount: 0, pageNumber, pageSize })
}

// Create a new batch and return the saved record. batchCode is
// system-generated by the backend — never sent by the client.
export function createBatch(input: BatchCreateInput): Promise<Batch> {
  if (MOCK_AUTH) {
    const batch: Batch = {
      batchGuid: crypto.randomUUID(),
      batchCode: `MOCK-${mockBatchSeq++}`,
      intProgram: input.intProgram,
      intSem: input.intSem,
      intStream: input.intStream,
      batchTime: input.batchTime,
      bStartDate: input.bStartDate,
      bEndDate: input.bEndDate,
      active: 1,
    }
    mockBatches.push(batch)
    return Promise.resolve(batch)
  }
  return apiPost<Batch>('/api/v1/academic/batches', input)
}

// Fetch one batch by its GUID.
export function getBatchById(guid: string): Promise<Batch> {
  if (MOCK_AUTH) {
    const existing = mockBatches.find(b => b.batchGuid === guid)
    if (!existing) return Promise.reject(new Error('Batch not found'))
    return Promise.resolve(existing)
  }
  return apiGet<Batch>(`/api/v1/academic/batches/${guid}`)
}

// Update a batch by GUID and return the updated record.
export function updateBatch(guid: string, input: BatchUpdateInput): Promise<Batch> {
  if (MOCK_AUTH) {
    const existing = mockBatches.find(b => b.batchGuid === guid)
    if (!existing) return Promise.reject(new Error('Batch not found'))
    existing.intStream = input.intStream
    existing.bStartDate = input.bStartDate
    existing.bEndDate = input.bEndDate
    return Promise.resolve(existing)
  }
  return apiPut<Batch>(`/api/v1/academic/batches/${guid}`, input)
}

// Delete a batch and return true when the API confirms success.
export function deleteBatch(guid: string): Promise<boolean> {
  if (MOCK_AUTH) {
    const index = mockBatches.findIndex(b => b.batchGuid === guid)
    if (index === -1) return Promise.reject(new Error('Batch not found'))
    mockBatches.splice(index, 1)
    return Promise.resolve(true)
  }
  return apiDelete<boolean>(`/api/v1/academic/batches/${guid}`)
}
