import { apiDelete, apiGet, apiPost, apiPut } from '../client'

const MOCK_AUTH = process.env.NEXT_PUBLIC_AUTH_MOCK === 'true'

// Confirmed via a real GET /api/v1/academic/batches response — the legacy
// intProgram/intSem/intStream/batchTime int FKs (with no confirmed guid
// counterpart) have been replaced with real guids on the read side too, not
// just Create/Update. A batch is students enrolled in a specific
// program-semester combination for a given intake.
export interface Batch {
  batchGuid: string
  batchCode: string
  programGuid: string
  semesterGuid: string
  streamGuid: string
  batchTimeGuid: string
  bStartDate: string | null
  bEndDate: string | null
  // 0/1 flag, not a multi-value enum — same convention as country.ts's
  // defaultCountry.
  active: number
}

interface BatchListResult {
  items: Batch[]
  totalCount: number
  pageNumber: number
  pageSize: number
}

// Confirmed via the updated Create/Update schema — programGuid/semesterGuid/
// streamGuid/batchTimeGuid are now real guids, resolving the old int-FK-
// with-no-guid-source gap for four of the five previously unconfirmed
// fields. bInCharge is still a plain number with no confirmed guid or real
// int source anywhere (Employee only ever exposes employeeGuid) — kept as
// the option's 1-based list position, same workaround as before, flagged
// in-UI. intakeCode is Intake.intakeCode, unchanged.
export interface BatchCreateInput {
  programGuid: string
  semesterGuid: string
  streamGuid: string
  batchTimeGuid: string
  bStartDate: string | null
  bEndDate: string | null
  bInCharge: number
  intakeCode: number
}

// Confirmed: Update now takes the identical shape as Create — a full
// replace, not the old narrower intStream/dates/bInCharge-only body where
// batchCode/batchTime were required but silently ignored. GET
// /batches/:guid now returns matching guid fields too (confirmed via a real
// list response — see Batch above), so EditBatchModal prefills Programme/
// Semester/Stream/Batch Time from the fetched record. Intake and Batch
// In-Charge still can't be prefilled — Batch's GET shape has no intake
// field at all, and no confirmed guid/int source for the employee either
// (see the note in NewBatchModal) — both must be re-picked on every edit.
export type BatchUpdateInput = BatchCreateInput

let mockBatchSeq = 1

const mockBatches: Batch[] = [
  { batchGuid: 'd7b04278-21ef-4cfa-8bee-ff336f08e344', batchCode: 'CSF26MRNA', programGuid: 'mock-program-1', semesterGuid: 'mock-semester-1', streamGuid: 'mock-stream-1', batchTimeGuid: 'mock-batchtime-1', bStartDate: '2024-02-12T00:00:00', bEndDate: '2024-06-07T00:00:00', active: 1 },
]

// Lists batches (paginated).
export function getBatches(pageNumber = 1, pageSize = 20): Promise<BatchListResult> {
  if (MOCK_AUTH) {
    return Promise.resolve({ items: mockBatches, totalCount: mockBatches.length, pageNumber, pageSize })
  }
  return apiGet<BatchListResult | null>(`/api/v1/academic/batches?pageNumber=${pageNumber}&pageSize=${pageSize}`)
    .then(data => data ?? { items: [], totalCount: 0, pageNumber, pageSize })
}

// Create a new batch and return the saved record. batchCode is
// system-generated by the backend — never sent by the client.
export function createBatch(input: BatchCreateInput): Promise<Batch> {
  if (MOCK_AUTH) {
    const batch: Batch = {
      batchGuid: crypto.randomUUID(),
      batchCode: `MOCK-${mockBatchSeq++}`,
      programGuid: input.programGuid,
      semesterGuid: input.semesterGuid,
      streamGuid: input.streamGuid,
      batchTimeGuid: input.batchTimeGuid,
      bStartDate: input.bStartDate,
      bEndDate: input.bEndDate,
      active: 1,
    }
    mockBatches.push(batch)
    return Promise.resolve(batch)
  }
  return apiPost<Batch>('/api/v1/academic/batches', input)
}

// Fetch one batch by its GUID.
export function getBatchById(guid: string): Promise<Batch> {
  if (MOCK_AUTH) {
    const existing = mockBatches.find(b => b.batchGuid === guid)
    if (!existing) return Promise.reject(new Error('Batch not found'))
    return Promise.resolve(existing)
  }
  return apiGet<Batch>(`/api/v1/academic/batches/${guid}`)
}

// Update a batch by GUID and return the updated record.
export function updateBatch(guid: string, input: BatchUpdateInput): Promise<Batch> {
  if (MOCK_AUTH) {
    const existing = mockBatches.find(b => b.batchGuid === guid)
    if (!existing) return Promise.reject(new Error('Batch not found'))
    existing.programGuid = input.programGuid
    existing.semesterGuid = input.semesterGuid
    existing.streamGuid = input.streamGuid
    existing.batchTimeGuid = input.batchTimeGuid
    existing.bStartDate = input.bStartDate
    existing.bEndDate = input.bEndDate
    return Promise.resolve(existing)
  }
  return apiPut<Batch>(`/api/v1/academic/batches/${guid}`, input)
}

// Delete a batch and return true when the API confirms success.
export function deleteBatch(guid: string): Promise<boolean> {
  if (MOCK_AUTH) {
    const index = mockBatches.findIndex(b => b.batchGuid === guid)
    if (index === -1) return Promise.reject(new Error('Batch not found'))
    mockBatches.splice(index, 1)
    return Promise.resolve(true)
  }
  return apiDelete<boolean>(`/api/v1/academic/batches/${guid}`)
}
